### PR TITLE
GUI bug fixes and scroll bars if small screen

### PR DESCRIPTION
**Pull request by lschaffer2**

### CODE REVIEW

**Comment by lschaffer2** [comment]
I'll take a look again on the smaller screen of my laptop and see if this fixes issues or try to fix it there

**Comment by acesnik** [comment]
Okay, let me know when you think it's ready to merge. If you push changes from you laptop, please double-check that it looks okay on your normal display.

**Comment by lschaffer2** [comment]
It's ready to merge, looked good on laptop

**Comment by acesnik** [comment]
Looks good.

**Pull request merged**
