### PR TITLE
added results summary, formatted dgv, fixed if user updates parameter, changed filepath in load-and-run method

### PR DESCRIPTION
**Pull request by lschaffer2**

### CODE REVIEW

**Comment by acesnik** [comment]
Hi Leah,

It looks like you got this error in the automated tests:
Test -> C:\projects\proteoform-suite\Test\bin\Release\Test.dll
ResultsSummary.cs(26,16): error CS0169: The field 'ResultsSummary.loadAndRunMethod' is never used [C:\projects\proteoform-suite\ProteoformSuiteGUI\ProteoformSuiteGUI.csproj]

Could you check whether your project builds and try to resolve this in another commit? Let me know if I can help.

Thanks,

Anthony

**Comment by lschaffer2** [comment]
It was an unused variable, so it didn't affect the build but looks like that causes an error. Looks like its fixed

**Comment by lschaffer2** [comment]
it looks like all neucode pairs were being aggregated, not just those within the boundaries set for intensity ratio/K-count (marked "accepted").

**Comment by acesnik** [comment]
Nice work on getting those column headers formatted!
- Could you change those methods to private, since they'll only be accessed in each of the forms?
- When you have the chance, could you implement formatting for the charge-state table and aggregated-component tables that are displayed when you click a row in those two forms? And the TheoreticalDatabase and EEComparison could also use formatting.

**Pull request merged**
